test_gpu_support fixes
charmed-kubernetes/jenkins pull request #1331
Opened 2023-05-25 13:07 UTC by kaskavel

Loop through all kubernetes-workers for nvidia and reboot if needed in test_gpu_support 

After a run in SQA's environment (jammy baremetal with charmed-kubernetes 1.27) with two NVIDIA T4 GPUs, we 've found that this test in order to pass needed: 

a) To check on all kubernetes-workers whether NVIDIA is present
b) To reboot the worker with the GPU node before nvidia-smi was usable. 

---
Mark below if this PR requires a job refresh (`jjb`) after merge:

- [ ] Needs `jjb` after merge

Please make sure to open PR's against the correct code:

- For integration tests, please make changes in `jobs/integration`
- For validation envs, `jobs/validate`
- For MicroK8s,`jobs/microk8s`
- For charm/bundle builds, `jobs/build-charms`

2023-05-26 14:29 UTC, addyess requested changes
@kaskavel Through no fault of your own, this test is a bit of a mess.  Could you help me clean it up?

2023-05-26 14:29 UTC, addyess commented on jobs/integration/validation.py
> +            break
Can we find all the nvidia workers like this

```suggestion
    # Find all nvidia based workers
    nvidia_workers = [
        unit
        for unit in model.applications["kubernetes-worker"].units
        if (await juju_run(unit, "lspci -nnk")).stdout.lower().count("nvidia")
    ]
```

2023-05-26 14:29 UTC, addyess commented on jobs/integration/validation.py
>      control_plane_unit = model.applications["kubernetes-control-plane"].units[0]
Then setup a `verify_argfs` which can be used in subsequent calls to `verify_deleted` and `verify_ready`
```suggestion
    control_plane_unit = model.applications["kubernetes-control-plane"].units[0]
    verify_args = (
        control_plane,
        "ds",
        ["nvidia-device-plugin-daemonset"],
        "-n kube-system",
```

2023-05-26 14:29 UTC, addyess commented on jobs/integration/validation.py
> +                ),
```suggestion
                verify_args,
```

2023-05-26 14:29 UTC, addyess commented on jobs/integration/validation.py
> +                ),
```suggestion
                verify_args,
```

2023-05-26 14:44 UTC, addyess commented on jobs/integration/validation.py
>      if not nvidia:
if there aren't any -- verify the daemonset isn't running

```suggestion
    if not nvidia_workers:
```

2023-05-26 18:22 UTC, addyess commented on jobs/integration/templates/nvidia-smi.yaml
> +        nvidia.com/gpu: 1
update the gpu test to use a later version of cuda

2023-05-26 18:45 UTC, addyess approved these changes
I have passed these tests on AWS multiple times now.
I even intentionally tried out what happens when the daemon-set isn't running at first, then reboot, then test again.

2023-05-26 18:46 UTC, addyess commented on jobs/integration/validation.py
> +            await machine_reboot(worker.machine, block=True)
reboot all the nvidia workers

2023-05-31 22:18 UTC, kwmonroe approved these changes

2023-05-31 22:18 UTC, merged